// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Analytics: typeof import('./src/views/Analytics.vue')['default']
    Container: typeof import('./src/components/Hydrogen/Container.vue')['default']
    ContentHeader: typeof import('./src/components/ContentHeader.vue')['default']
    CRFDAvatar: typeof import('./src/components/CRFD/CRFDAvatar.vue')['default']
    CRFDBox: typeof import('./src/components/CRFD/CRFDBox.vue')['default']
    CRFDButton: typeof import('./src/components/CRFD/CRFDButton.vue')['default']
    CRFDCard: typeof import('./src/components/CRFD/CRFDCard.vue')['default']
    CRFDCheckbox: typeof import('./src/components/CRFD/CRFDCheckbox.vue')['default']
    CRFDCommandPalette: typeof import('./src/components/CRFD/CRFDCommandPalette.vue')['default']
    CRFDDetail: typeof import('./src/components/CRFD/CRFDDetail.vue')['default']
    CRFDDropdown: typeof import('./src/components/CRFD/CRFDDropdown.vue')['default']
    CRFDHazardDiamond: typeof import('./src/components/CRFD/CRFDHazardDiamond.vue')['default']
    CRFDIcon: typeof import('./src/components/CRFD/CRFDIcon.vue')['default']
    CRFDIndicator: typeof import('./src/components/CRFD/CRFDIndicator.vue')['default']
    CRFDInput: typeof import('./src/components/CRFD/CRFDInput.vue')['default']
    CRFDLabel: typeof import('./src/components/CRFD/CRFDLabel.vue')['default']
    CRFDLibraryDetail: typeof import('./src/components/CRFD/CRFDLibraryDetail.vue')['default']
    CRFDMap: typeof import('./src/components/CRFD/CRFDMap.vue')['default']
    CRFDModifier: typeof import('./src/components/CRFD/CRFDModifier.vue')['default']
    CRFDNavbar: typeof import('./src/components/CRFD/CRFDNavbar.vue')['default']
    CRFDPath: typeof import('./src/components/CRFD/CRFDPath.vue')['default']
    CRFDSpinner: typeof import('./src/components/CRFD/CRFDSpinner.vue')['default']
    CRFDTemplate: typeof import('./src/components/CRFD/CRFDTemplate.vue')['default']
    CRFDTextarea: typeof import('./src/components/CRFD/CRFDTextarea.vue')['default']
    CRFDTooltip: typeof import('./src/components/CRFD/CRFDTooltip.vue')['default']
    DataTable: typeof import('./src/components/DataTable.vue')['default']
    ElementPreview: typeof import('./src/components/ElementPreview.vue')['default']
    Index: typeof import('./src/views/Index.vue')['default']
    InPageNavigationLayout: typeof import('./src/layouts/InPageNavigationLayout.vue')['default']
    Login: typeof import('./src/views/Login.vue')['default']
    LoremIpsum: typeof import('./src/components/LoremIpsum.vue')['default']
    Map: typeof import('./src/views/Map.vue')['default']
    Markdown: typeof import('./src/components/Markdown.vue')['default']
    NewOperation: typeof import('./src/views/NewOperation.vue')['default']
    NewSpace: typeof import('./src/views/NewSpace.vue')['default']
    Operations: typeof import('./src/views/Operations.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    RightDetailLayout: typeof import('./src/layouts/RightDetailLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/views/Settings.vue')['default']
    Spaces: typeof import('./src/views/Spaces.vue')['default']
    TableLayout: typeof import('./src/layouts/TableLayout.vue')['default']
  }
}

export {}
